name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2

  # скачать файл
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

  # открыть файл
  open_file: ^3.2.1

  # сохранить файл
  path_provider: ^2.0.14

dev_dependencies:


  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
